app_title: ISO 55013 资产管理体系评估工具
section_scores: 各章节得分
total_score: 总分
save_progress: 保存当前进度
load_progress: 加载上次进度
progress_saved: 进度已保存！
progress_loaded: 已加载上次保存的进度！
report_title: ISO 55013 评估报告
report_generate_time: 生成时间
radar_chart: 雷达图
section_table: 章节得分表
assessment_detail: 详细评估结果
export_pdf: 导出PDF报告
export_excel: 导出Excel报告
zh_button: 中文
en_button: English
last_saved: 上次保存时间
system_assessment: 体系评估
result_analysis: 结果分析
report_export: 报告导出
generate_excel_report: 生成Excel报告
generating_excel_report: 正在生成Excel报告...
download_excel_report: 下载Excel报告
excel_report_generated: Excel报告生成成功
error_generating_excel_report: 生成Excel报告时出错
radar_chart_data: 雷达图数据
assessment_results: 评估结果
generate_pdf_report: 生成PDF报告
generating_pdf_report: 正在生成PDF报告...
download_pdf_report: 下载PDF报告
pdf_report_generated: PDF报告生成成功
failed_generating_pdf_report: 生成PDF报告失败
overall_score: 总体评分
element_scores: 要素得分
cannot_generate_radar_chart: 无法生成雷达图
score: 评分
question: 问题
type: 类型
weight: 分值权重
sub_question_scores: 子问题得分
answer_yes: 是
answer_no: 否
progress_auto_saved: 进度已自动保存
last_progress_loaded: 已加载上次保存的进度！
error_saving_progress: 保存进度时出错
error_loading_progress: 加载进度时出错
element_scores_detail: 各要素得分详情
detailed_assessment_results: 详细评估结果
element: 要素